### ISSUE TITLE
Problém s odkazy u cvičení 4.2 a 4.3 na nové verzi

### ISSUE THREAD

**Issue by hlavacm** [podlomar/novekodim#4]
Ahoj @podlomar, 

Při přípravě na 4. lekci [První programy](http://nove.kodim.cz/czechitas/python-data/zaklady-programovani/prvni-programy), jsem u cvičení [2](http://nove.kodim.cz/czechitas/python-data/zaklady-programovani/prvni-programy/#exc-vyplata-jako-program) a [3](http://nove.kodim.cz/czechitas/python-data/zaklady-programovani/prvni-programy/#exc-teploty-jako-program) narazil na nefunkční odkazy v případě nové verze webu. Na staré verzi odkazy u obou cvičení fungují správně… 

Viz společné obsahové soubory: [vyplata-jako-program.md](https://github.com/podlomar/python-data/blob/master/zaklady-programovani/prvni-programy/excs/vyplata-jako-program.md) resp. [teploty-jako-program.md](https://github.com/podlomar/python-data/blob/master/zaklady-programovani/prvni-programy/excs/teploty-jako-program.md)

a původní odkazy: http://nove.kodim.cz/czechitas/python-data/hodnoty-promenne-funkce#cvi-vyplata, resp. http://nove.kodim.cz/czechitas/python-data/text-chroustani#cvi-seznam-teplot

ale nová struktura: http://nove.kodim.cz/czechitas/python-data/zaklady-programovani/hodnoty-promenne-funkce/#exc-vyplata, resp. http://nove.kodim.cz/czechitas/python-data/zaklady-programovani/text-chroustani/#exc-seznam-teplot

**Comment by podlomar** [comment]
Děkuju za report. Opraveno.
